build:
    environment:
        php: '5.6'
    tests:
        before:
            - 'composer update'
filter:
    excluded_paths:
        - tests/*
        - vendor/*

tools:
    external_code_coverage: true
